FROM python:3.9-slim

WORKDIR /opt/puzzle-api

ARG MONGO_URL
ARG MONGO_DB_NAME
ARG BUCKET_NAME
ARG CDN_ACCESS_KEY_ID
ARG CDN_BASE_URL
ARG CDN_ENDPOINT_URL
ARG CDN_REGION_NAME
ARG CDN_SECRET_ACCESS_KEY

ENV MONGO_URL=$MONGO_URL
ENV MONGO_DB_NAME=$MONGO_DB_NAME
ENV BUCKET_NAME=$BUCKET_NAME
ENV CDN_ACCESS_KEY_ID=$CDN_ACCESS_KEY_ID
ENV CDN_BASE_URL=$CDN_BASE_URL
ENV CDN_ENDPOINT_URL=$CDN_ENDPOINT_URL
ENV CDN_REGION_NAME=$CDN_REGION_NAME
ENV CDN_SECRET_ACCESS_KEY=$CDN_SECRET_ACCESS_KEY

ADD . /opt/puzzle-api

USER root

RUN pip install -r /opt/puzzle-api/requirements.txt

EXPOSE 8001

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
